package com.dante.paul.dd5erandomlootgeneratorpremium.EnumeratedClasses;

/**
 * Created by pdante on 5/31/2018.
 */

public enum TypeOfItem {
    HEADGEAR, BELT, MAGIC_ITEM, SPELL, ART, OIL, SWORD, AXE, HAMMER, DAGGER, STAFF, ENCHANTED, NOT_ENCHANTED, IOUN, TALISMAN, NECKLACE, BOOTS, POTION, SCROLL, OTHER, AMMO, JEWELRY, ARMOR, RING, ROBE, WAND, WEAPON, SHIELD, GLOVES, INSTRUMENT, CLOAK, ROD, STONE, TOME, NA, GEM, DUST, CLOTHING, LEGENDARY, WONDEROUS,

    PHB, SCAG, XGE,

    BASE
}
